from django.urls import path
from .models import (
    UserProfile,
    Education,
    Experience,
    Project,
    ProfileLink,
    Certification
)
from .forms import (
    UserProfileForm,
    EducationForm,
    ExperienceForm,
    ProjectForm,
    ProfileLinkForm,
    CertificationForm
)
from .views import (
    HomeView,
    UserProfileView,
    AddInstanceView,
    AddSkillView,
    UpdateInstance,
    delete_skill,
    SendEmailView
)

app_name = 'portfolio_app'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('user/', HomeView.as_view(), name='user-home'),
    path('user_profile/', UserProfileView.as_view(), name='profile'),
    path('add-education/',
         AddInstanceView.as_view(model=Education,
                                 template_name='education_form.html',
                                 form_class=EducationForm), name='education'),
    path('add-experience/',
         AddInstanceView.as_view(model=Experience,
                                 template_name='experience_form.html',
                                 form_class=ExperienceForm), name='experience'),
    path('add-project/',
         AddInstanceView.as_view(model=Project,
                                 template_name='project_form.html',
                                 form_class=ProjectForm), name='project'),
    path('add-profilelink/',
         AddInstanceView.as_view(model=ProfileLink,
                                 template_name='profilelink_form.html',
                                 form_class=ProfileLinkForm), name='profilelink'),
    path('add-certification/', AddInstanceView.as_view(model=Certification,
                                                       template_name='certification_form.html',
                                                       form_class=CertificationForm), name='certification'),
    path('update-userprofile/<int:pk>/',
         UpdateInstance.as_view(model=UserProfile,
                                template_name='user_profile_form.html',
                                form_class=UserProfileForm), name="update-userprofile"),
    path('update-education/<int:pk>/',
         UpdateInstance.as_view(model=Education,
                                template_name='education_form.html',
                                form_class=EducationForm), name='update-education'),
    path('update-experience/<int:pk>/',
         UpdateInstance.as_view(model=Experience,
                                template_name='experience_form.html',
                                form_class=ExperienceForm), name='update-experience'),
    path('update-project/<int:pk>/',
         UpdateInstance.as_view(model=Project,
                                template_name='project_form.html',
                                form_class=ProjectForm), name='update-project'),
    path('update-profilelink/<int:pk>/',
         UpdateInstance.as_view(model=ProfileLink,
                                template_name='profilelink_form.html',
                                form_class=ProfileLinkForm), name='update-profilelink'),
    path('update-certification/<int:pk>/',
         UpdateInstance.as_view(model=Certification,
                                template_name='certification_form.html',
                                form_class=CertificationForm), name='update-certification'),
    path('add-skill/', AddSkillView.as_view(), name='skill'),
    path('delete-skill/<int:pk>/', delete_skill, name='delete-skill'),
    path('send-email/', SendEmailView.as_view(), name="send-email"),
]
