# Generated by Django 3.0.7 on 2020-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='out_of',
            field=models.CharField(choices=[('Four', '4.0'), ('Five', '5.0')], max_length=4),
        ),
    ]
