# Generated by Django 3.0.7 on 2020-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20201102_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
