# Generated by Django 3.0.7 on 2020-11-03 09:44

from django.db import migrations, models
import portfolio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20201102_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=portfolio_app.models.upload_project_image_to),
        ),
    ]
