# Generated by Django 3.0.7 on 2020-11-09 07:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20201105_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
