# Generated by Django 3.0.7 on 2020-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_auto_20201109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
