# Generated by Django 3.0.7 on 2020-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_auto_20201207_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('2.1', 'Masters Degree'), ('2.2', 'Master of Science'), ('3.1', 'Bachelor Degree'), ('3.2', 'Bachelor of Science'), ('3.3', 'Bachelor in Business Administration'), ('3.4', 'Bachelor in Arts'), ('4.1', 'Diploma Degree'), ('5.1', 'Higher Secondary Certificate'), ('5.2', 'A Level'), ('6.1', 'Secondary School Certificate'), ('6.2', 'O Level'), ('7.1', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='out_of',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
